In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/akarapusreenija/superstore-sales-dataset/SuperStoreOrders.csv

In [2]:
import pandas as pd

df = pd.read_csv("/kaggle/input/datasets/akarapusreenija/superstore-sales-dataset/SuperStoreOrders.csv")

In [3]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [4]:
df.shape

(51290, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [6]:
df["sales"].head(10)

0    408
1    120
2     66
3     45
4    114
5     55
6    314
7    276
8    912
9    667
Name: sales, dtype: object

In [7]:
df["sales"].sample(10, random_state=42)

49728       86
45547       18
15664       20
40561       60
49426    1,791
18956      171
14238       10
31818    1,220
41388        7
37236       57
Name: sales, dtype: object

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

In [10]:
df["order_date"].head(20)

0     1/1/2011
1     1/1/2011
2     1/1/2011
3     1/1/2011
4     1/1/2011
5     1/1/2011
6     2/1/2011
7     3/1/2011
8     3/1/2011
9     3/1/2011
10    3/1/2011
11    3/1/2011
12    3/1/2011
13    3/1/2011
14    3/1/2011
15    3/1/2011
16    3/1/2011
17    3/1/2011
18    3/1/2011
19    3/1/2011
Name: order_date, dtype: object

In [11]:
df[df["order_date"].str.contains("-")]["order_date"].head(20)

162    13-01-2011
163    13-01-2011
164    13-01-2011
165    13-01-2011
166    13-01-2011
167    13-01-2011
168    13-01-2011
169    13-01-2011
170    13-01-2011
171    13-01-2011
172    13-01-2011
173    14-01-2011
174    14-01-2011
175    14-01-2011
176    14-01-2011
177    14-01-2011
178    14-01-2011
179    14-01-2011
180    14-01-2011
181    14-01-2011
Name: order_date, dtype: object

In [12]:
# Dates with '/'
df["order_date"].str.contains("/").sum()

np.int64(20067)

In [13]:
# Dates with '-'
df["order_date"].str.contains("-").sum()

np.int64(31223)

In [14]:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    format="mixed",
    dayfirst=True
)

df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    format="mixed",
    dayfirst=True
)

In [15]:
df[["order_date", "ship_date"]].dtypes

order_date    datetime64[ns]
ship_date     datetime64[ns]
dtype: object

In [16]:
df["sales"] = df["sales"].str.replace(",", "")

In [17]:
df["sales"].sample(10, random_state=42)

49728      86
45547      18
15664      20
40561      60
49426    1791
18956     171
14238      10
31818    1220
41388       7
37236      57
Name: sales, dtype: object

In [18]:
df["sales"] = pd.to_numeric(df["sales"])

In [19]:
df["sales"].dtype

dtype('int64')

In [20]:
df.dtypes

order_id                  object
order_date        datetime64[ns]
ship_date         datetime64[ns]
ship_mode                 object
customer_name             object
segment                   object
state                     object
country                   object
market                    object
region                    object
product_id                object
category                  object
sub_category              object
product_name              object
sales                      int64
quantity                   int64
discount                 float64
profit                   float64
shipping_cost            float64
order_priority            object
year                       int64
dtype: object

In [21]:
customers_df = df[
    [
        "customer_name",
        "segment",
        "state",
        "country",
        "market",
        "region",
    ]
].drop_duplicates()

In [22]:
customers_df.head()

     customer_name      segment            state    country  market   region
0  Toby Braunhardt     Consumer      Constantine    Algeria  Africa   Africa
1      Joseph Holt     Consumer  New South Wales  Australia    APAC  Oceania
2    Annie Thurman     Consumer         Budapest    Hungary    EMEA     EMEA
3     Eugene Moren  Home Office        Stockholm     Sweden      EU    North
6  Magdelene Morse     Consumer          Ontario     Canada  Canada   Canada

In [23]:
customers_df.shape

(23364, 6)

In [24]:
customers_df = customers_df.reset_index(drop=True)

In [25]:
customers_df.head()

     customer_name      segment            state    country  market   region
0  Toby Braunhardt     Consumer      Constantine    Algeria  Africa   Africa
1      Joseph Holt     Consumer  New South Wales  Australia    APAC  Oceania
2    Annie Thurman     Consumer         Budapest    Hungary    EMEA     EMEA
3     Eugene Moren  Home Office        Stockholm     Sweden      EU    North
4  Magdelene Morse     Consumer          Ontario     Canada  Canada   Canada

In [26]:
customers_df["customer_id"] = [
    f"C{i:05d}" for i in range(1, len(customers_df) + 1)
]

In [27]:
customers_df.head()

,customer_name,segment,state,country,market,region,customer_id
0,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,C00001
1,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,C00002
2,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,C00003
3,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,C00004
4,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,C00005

In [28]:
products_df = df[
    [
        "product_id",
        "category",
        "sub_category",
        "product_name",
    ]
].drop_duplicates()

In [29]:
products_df = products_df.reset_index(drop=True)

In [30]:
products_df.head()
products_df.shape

(10768, 4)

In [31]:
orders_df = df.merge(
    customers_df[["customer_id", "customer_name"]],
    on="customer_name",
    how="left"
)

In [32]:
orders_df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,customer_id
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408,2,0.0,106.14,35.46,Medium,2011,C00001
1,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408,2,0.0,106.14,35.46,Medium,2011,C00309
2,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408,2,0.0,106.14,35.46,Medium,2011,C00374
3,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408,2,0.0,106.14,35.46,Medium,2011,C01285
4,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408,2,0.0,106.14,35.46,Medium,2011,C01543

In [33]:
customers_df["customer_name"].duplicated().sum()

np.int64(22569)

In [34]:
customers_df[customers_df["customer_name"].duplicated(keep=False)].sort_values("customer_name").head(20)

,customer_name,segment,state,country,market,region,customer_id
17349,Aaron Bergman,Consumer,Campania,Italy,EU,South,C17350
22883,Aaron Bergman,Consumer,San Salvador,El Salvador,LATAM,Central,C22884
12746,Aaron Bergman,Consumer,Nord-Pas-de-Calais,France,EU,Central,C12747
14194,Aaron Bergman,Consumer,Provence-Alpes-Côte d'Azur,France,EU,Central,C14195
6663,Aaron Bergman,Consumer,Qom,Iran,EMEA,EMEA,C06664
16707,Aaron Bergman,Consumer,Saarland,Germany,EU,Central,C16708
18600,Aaron Bergman,Consumer,Sumatera Selatan,Indonesia,APAC,Southeast Asia,C18601
562,Aaron Bergman,Consumer,Sicily,Italy,EU,South,C00563
11439,Aaron Bergman,Consumer,Santa Fe,Argentina,LATAM,South,C11440
20273,Aaron Bergman,Consumer,Karnataka,India,APAC,Central Asia,C20274
14729,Aaron Bergman,Consumer,Centre,Cameroon,Africa,Africa,C14730
5273,Aaron Bergman,Consumer,Copperbelt,Zambia,Africa,Africa,C05274
7109,Aaron Bergman,Consumer,North Brabant,Netherlands,EU,Central,C07110
16309,Aaron Bergman,Consumer,Dà Nang,Vietnam,APAC,Southeast Asia,C16310
4519,Aaron Bergman,Consumer,Maharashtra,India,APAC,Central Asia,C04520
9550,Aaron Bergman,Consumer,Bangkok,Thailand,APAC,Southeast Asia,C09551
6171,Aaron Bergman,Consumer,Hubei,China,APAC,North Asia,C06172
12344,Aaron Bergman,Consumer,Telangana,India,APAC,Central Asia,C12345
16345,Aaron Bergman,Consumer,Ile-de-France,France,EU,Central,C16346
15996,Aaron Bergman,Consumer,León,Nicaragua,LATAM,Central,C15997

In [35]:
orders_df = orders_df.drop(
    columns=[
        "product_name",
        "category",
        "sub_category"
    ]
)

In [36]:
orders_df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,sales,quantity,discount,profit,shipping_cost,order_priority,year,customer_id
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,408,2,0.0,106.14,35.46,Medium,2011,C00001
1,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,408,2,0.0,106.14,35.46,Medium,2011,C00309
2,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,408,2,0.0,106.14,35.46,Medium,2011,C00374
3,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,408,2,0.0,106.14,35.46,Medium,2011,C01285
4,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,408,2,0.0,106.14,35.46,Medium,2011,C01543

In [37]:
orders_df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'sales', 'quantity', 'discount', 'profit', 'shipping_cost',
       'order_priority', 'year', 'customer_id'],
      dtype='object')

In [38]:
products_df.to_csv("products.csv", index=False)

In [39]:
orders_df.to_csv("orders.csv", index=False)

In [40]:
df.shape

(51290, 21)

In [41]:
orders_df.shape

(1546158, 19)

In [42]:
orders_df = df.copy()

In [43]:
orders_df = orders_df.drop(
    columns=[
        "product_name",
        "category",
        "sub_category"
    ]
)

In [44]:
orders_df.shape

(51290, 18)

In [45]:
products_df.to_csv("products.csv", index=False)
orders_df.to_csv("orders.csv", index=False)

In [46]:
import os

os.listdir()

['__notebook__.ipynb', 'orders.csv', 'products.csv']

In [47]:
import sqlite3

In [48]:
conn = sqlite3.connect("retail_sales.db")

In [49]:
type(conn)

sqlite3.Connection

In [50]:
products_df.to_sql(
    "products",
    conn,
    if_exists="replace",
    index=False
)

10768

In [51]:
pd.read_sql(
    "SELECT * FROM products LIMIT 5;",
    conn
)

         product_id         category sub_category                 product_name
0  OFF-TEN-10000025  Office Supplies      Storage          Tenex Lockers, Blue
1   OFF-SU-10000618  Office Supplies     Supplies     Acme Trimmer, High Speed
2  OFF-TEN-10001585  Office Supplies      Storage      Tenex Box, Single Width
3   OFF-PA-10001492  Office Supplies        Paper  Enermax Note Cards, Premium
4   FUR-FU-10003447        Furniture  Furnishings   Eldon Light Bulb, Duo Pack

In [52]:
orders_df.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

51290

In [53]:
pd.read_sql(
    "SELECT * FROM orders LIMIT 5;",
    conn
)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01 00:00:00,2011-01-06 00:00:00,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,2011-01-01 00:00:00,2011-01-05 00:00:00,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,2011-01-01 00:00:00,2011-01-05 00:00:00,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,OFF-PA-10001492,45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,FUR-FU-10003447,114,5,0.1,37.770,4.70,Medium,2011

In [54]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_products
    FROM products;
    """,
    conn
)

   total_products
0           10768

In [55]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_orders
    FROM orders;
    """,
    conn
)

   total_orders
0         51290

In [56]:
pd.read_sql("""
SELECT SUM(sales) AS total_sales
FROM orders;
""", conn)

   total_sales
0     12642905

In [57]:
pd.read_sql("""
SELECT AVG(profit) AS average_profit
FROM orders;
""", conn)

   average_profit
0        28.64174

In [58]:
pd.read_sql("""
SELECT MAX(sales) AS highest_sale
FROM orders;
""", conn)

   highest_sale
0         22638

In [59]:
pd.read_sql("""
SELECT
    region,
    SUM(sales) AS total_sales
FROM orders
GROUP BY region
ORDER BY total_sales DESC;
""", conn)

            region  total_sales
0          Central      2822399
1            South      1600960
2            North      1248192
3          Oceania      1100207
4   Southeast Asia       884438
5       North Asia       848349
6             EMEA       806184
7           Africa       783776
8     Central Asia       752839
9             West       725514
10            East       678834
11       Caribbean       324281
12          Canada        66932

In [60]:
pd.read_sql("""
SELECT
    market,
    COUNT(*) AS total_orders
FROM orders
GROUP BY market
ORDER BY total_orders DESC;
""", conn)

   market  total_orders
0    APAC         11002
1   LATAM         10294
2      EU         10000
3      US          9994
4    EMEA          5029
5  Africa          4587
6  Canada           384

In [61]:
pd.read_sql("""
SELECT
    p.product_name,
    SUM(o.sales) AS total_sales
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sales DESC
LIMIT 10;
""", conn)

                                        product_name  total_sales
0                       Apple Smart Phone, Full Size        86936
1                       Cisco Smart Phone, Full Size        76441
2                    Motorola Smart Phone, Full Size        73159
3                       Nokia Smart Phone, Full Size        71904
4              Canon imageCLASS 2200 Advanced Copier        61600
5         Hon Executive Leather Armchair, Adjustable        58200
6  Office Star Executive Leather Armchair, Adjust...        51455
7  Harbour Creations Executive Leather Armchair, ...        50120
8                      Samsung Smart Phone, Cordless        48654
9                  Nokia Smart Phone, with Caller ID        47880

In [62]:
pd.read_sql("""
SELECT
    category,
    SUM(sales) AS total_sales
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY category
ORDER BY total_sales DESC;
""", conn)

          category  total_sales
0       Technology      5178045
1        Furniture      4502915
2  Office Supplies      4172336

In [63]:
pd.read_sql("""
SELECT
    p.category,
    ROUND(SUM(o.profit), 2) AS total_profit
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_profit DESC;
""", conn)

          category  total_profit
0       Technology     723147.93
1  Office Supplies     575902.63
2        Furniture     309954.22

In [64]:
pd.read_sql("""
SELECT
    market,
    ROUND(AVG(discount), 2) AS avg_discount
FROM orders
GROUP BY market
ORDER BY avg_discount DESC;
""", conn)

   market  avg_discount
0    EMEA          0.20
1      US          0.16
2  Africa          0.16
3    APAC          0.15
4   LATAM          0.14
5      EU          0.10
6  Canada          0.00

In [65]:
pd.read_sql("""
SELECT
    p.product_name,
    ROUND(SUM(o.profit), 2) AS total_profit
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_profit DESC
LIMIT 5;
""", conn)

                            product_name  total_profit
0  Canon imageCLASS 2200 Advanced Copier      25199.93
1           Cisco Smart Phone, Full Size      17238.52
2        Motorola Smart Phone, Full Size      17027.11
3                      Hoover Stove, Red      11651.68
4   Sauder Classic Bookcase, Traditional      10672.07

In [66]:
pd.read_sql("""
SELECT
    p.category,
    SUM(o.sales) AS total_sales,
    ROUND(SUM(o.profit), 2) AS total_profit
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_sales DESC;
""", conn)

          category  total_sales  total_profit
0       Technology      5178045     723147.93
1        Furniture      4502915     309954.22
2  Office Supplies      4172336     575902.63

In [67]:
pd.read_sql("""
SELECT
    region,
    COUNT(*) AS total_orders
FROM orders
GROUP BY region
HAVING COUNT(*) > 5000
ORDER BY total_orders DESC;
""", conn)

    region  total_orders
0  Central         11117
1    South          6645
2     EMEA          5029

In [68]:
pd.read_sql("""
SELECT
    COUNT(DISTINCT country) AS total_countries
FROM orders;
""", conn)

   total_countries
0              147

In [69]:
pd.read_sql("""
SELECT
    order_id,
    profit,
    CASE
        WHEN profit > 0 THEN 'Profitable'
        ELSE 'Loss'
    END AS order_status
FROM orders
LIMIT 10;
""", conn)

          order_id   profit order_status
0     AG-2011-2040  106.140   Profitable
1    IN-2011-47883   36.036   Profitable
2     HU-2011-1220   29.640   Profitable
3  IT-2011-3647632  -26.055         Loss
4    IN-2011-47883   37.770   Profitable
5    IN-2011-47883   15.342   Profitable
6     CA-2011-1510    3.120   Profitable
7    IN-2011-79397  110.412   Profitable
8    ID-2011-80230 -319.464         Loss
9     IZ-2011-4680  253.320   Profitable

In [70]:
pd.read_sql("""
SELECT
    CASE
        WHEN profit > 0 THEN 'Profitable'
        ELSE 'Loss'
    END AS order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;
""", conn)

  order_status  total_orders
0         Loss         13211
1   Profitable         38079